project:
  type: website
  output-dir : docs

website:
  title: "Site météo de Jeanne"
  site-url: https://jeannemann.github.io/Projet-perso/
  repo-url: https://github.com/jeannemann/Projet-perso
  page-navigation: true
  repo-actions: [source, issue]
  
format:
  html:
    theme:
      - cosmo
    css: style.css
    html-math-method: katex
    toc-location: right
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    fig-responsive: true
    fig.align: center

editor: visual
