name: Render & Publish Quarto Site

on:
  schedule:
    - cron: '0 2 * * *'  # tous les jours à 2h UTC (tu peux changer)
  workflow_dispatch:

permissions:
  contents: write  # pour pousser les fichiers
  pages: write     # autorise déploiement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openmeteo_requests requests-cache retry_requests pandas jupyter pyyaml

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.57'  # spécifie la version de Quarto

      - name: Render site
        run: quarto render --no-cache

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
